#!/usr/bin/env bash
set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
REPO_ROOT="$(cd "${SCRIPT_DIR}/.." && pwd)"
OUT_FILE="${REPO_ROOT}/constraints-ci.txt"
TMP_VENV="$(mktemp -d /tmp/qiskit-v2-constraints-XXXXXX)"

cleanup() {
  rm -rf "${TMP_VENV}"
}
trap cleanup EXIT

python3 -m venv "${TMP_VENV}"
source "${TMP_VENV}/bin/activate"

python -m pip install --upgrade pip
python -m pip install -r "${REPO_ROOT}/requirements.txt"

{
  echo "# Generated by scripts/update_constraints_ci.sh"
  echo "# Python: $(python --version 2>&1)"
  echo "# Regenerate with: bash scripts/update_constraints_ci.sh"
  echo
  python -m pip freeze --all | LC_ALL=C sort
} > "${OUT_FILE}"

echo "Wrote ${OUT_FILE}"
